# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_fsm_log', '0002_auto_20151207_1521'),
        ('django_fsm_log', '0002_auto_20150407_1013'),
    ]

    operations = [
    ]
