# Generated by Django 2.2.24 on 2021-09-01 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_fsm_log', '0003_statelog_description_squashed_0005_description_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statelog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='statelog',
            name='transition',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
