# Generated by Django 2.1.5 on 2019-01-31 03:41

from django.db import migrations
import django_fsm_log.managers


class Migration(migrations.Migration):

    dependencies = [
        ('django_fsm_log', '0003_statelog_description_squashed_0005_description_null'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='statelog',
            managers=[
                ('objects', django_fsm_log.managers.StateLogManager()),
            ],
        ),
    ]
